title: "Abdelkbir HADIOUI"
logo: Ma photo_pro.png
description: "Portfolio Ingénieur Génie Mécanique et Systèmes Automatisés | Automatisation industrielle, Robotique, Maintenance et Industrie 4.0"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
